Importing Libraries


In [1]:
import pandas as pd
import numpy as np
import pickle

Importing the files


In [2]:
train=pd.read_csv(r"C:\Users\neelu\Documents\VIT stuff\sem4\ML\Classification\input\train.csv")
test=pd.read_csv(r"C:\Users\neelu\Documents\VIT stuff\sem4\ML\Classification\input\test.csv")

Removing random indices generated 
 

In [3]:
test

Unnamed: 0  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0          225          0.916995        -0.541564           1.074194   
1          133         -0.786161         0.373872          -0.569284   
2           29         -1.390507        -0.083846          -0.426373   
3          145         -0.456518         0.679017           0.002360   
4          104         -1.079177        -0.338134          -0.212006   
..         ...               ...              ...                ...   
60         210         -0.090248         0.475587           0.073816   
61          98         -1.115804         0.729875          -0.569284   
62         120         -0.950982         0.221299          -0.712196   
63         239          0.385904        -1.050140           1.002739   
64         170          0.495785         0.373872          -0.426373   

    body_mass_g  island  species  sex  
0      1.670315     0.0      2.0  0.0  
1      0.053411     1.0      0.0  1.0  
2     -1.097078     0.0      0.0  1.0  
3     -0.257532     1.0      0.0  1.0  
4     -0.475192     0.0      0.0  0.0  
..          ...     ...      ...  ...  
60    -1.003795     1.0      1.0  1.0  
61    -1.594587     1.0      0.0  0.0  
62    -1.159266     2.0      0.0  0.0  
63     1.110617     0.0      2.0  1.0  
64    -1.128172     1.0      1.0  0.0  

[65 rows x 8 columns]

In [4]:
test=test.drop(['Unnamed: 0'],axis=1)


In [5]:
test

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g  island  \
0           0.916995        -0.541564           1.074194     1.670315     0.0   
1          -0.786161         0.373872          -0.569284     0.053411     1.0   
2          -1.390507        -0.083846          -0.426373    -1.097078     0.0   
3          -0.456518         0.679017           0.002360    -0.257532     1.0   
4          -1.079177        -0.338134          -0.212006    -0.475192     0.0   
..               ...              ...                ...          ...     ...   
60         -0.090248         0.475587           0.073816    -1.003795     1.0   
61         -1.115804         0.729875          -0.569284    -1.594587     1.0   
62         -0.950982         0.221299          -0.712196    -1.159266     2.0   
63          0.385904        -1.050140           1.002739     1.110617     0.0   
64          0.495785         0.373872          -0.426373    -1.128172     1.0   

    species  sex  
0       2.0  0.0  
1       0.0  1.0  
2       0.0  1.0  
3       0.0  1.0  
4       0.0  0.0  
..      ...  ...  
60      1.0  1.0  
61      0.0  0.0  
62      0.0  0.0  
63      2.0  1.0  
64      1.0  0.0  

[65 rows x 7 columns]

In [6]:
train.head()

Unnamed: 0  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0         220          0.257709        -1.304427           0.716916   
1         163          2.565211         0.323014          -1.426752   
2         137         -0.603026        -0.083846          -0.783651   
3          41         -0.529772         0.933305          -1.355296   
4          15         -1.134117         0.577302          -1.926941   

   body_mass_g  island  species  sex  
0     0.737486     0.0      2.0  0.0  
1    -0.630663     1.0      1.0  1.0  
2    -0.599569     1.0      0.0  1.0  
3    -0.972701     1.0      0.0  1.0  
4    -1.003795     2.0      0.0  0.0

In [7]:
train=train.drop(['Unnamed: 0'],axis=1)

In [8]:
train.head()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g  island  \
0          0.257709        -1.304427           0.716916     0.737486     0.0   
1          2.565211         0.323014          -1.426752    -0.630663     1.0   
2         -0.603026        -0.083846          -0.783651    -0.599569     1.0   
3         -0.529772         0.933305          -1.355296    -0.972701     1.0   
4         -1.134117         0.577302          -1.926941    -1.003795     2.0   

   species  sex  
0      2.0  0.0  
1      1.0  1.0  
2      0.0  1.0  
3      0.0  1.0  
4      0.0  0.0

K-Nearest Neighbours


In [9]:
Xtrain=train.drop('species',axis=1)
Xtest=test.drop('species',axis=1)
Ytrain=train[['species']]
Ytest=test[['species']]

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(Xtrain,Ytrain)
preds_knn = knn.predict(Xtest)
print(confusion_matrix(Ytest,preds_knn))

[[28  2  0]
 [ 4  9  1]
 [ 0  0 21]]


C:\Users\neelu\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [11]:
print(classification_report(Ytest,preds_knn))

              precision    recall  f1-score   support

         0.0       0.88      0.93      0.90        30
         1.0       0.82      0.64      0.72        14
         2.0       0.95      1.00      0.98        21

    accuracy                           0.89        65
   macro avg       0.88      0.86      0.87        65
weighted avg       0.89      0.89      0.89        65



In [12]:
print(accuracy_score(Ytest,preds_knn))

0.8923076923076924


In [13]:
pickle.dump(knn,open(r"C:\Users\neelu\Documents\VIT stuff\sem4\ML\Project 1\model\KNN.pkl",'wb'))

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\neelu\\Documents\\VIT stuff\\sem4\\ML\\Project 1\\model\\KNN.pkl'

Logistic Regression

In [ ]:
Ytrain1=train.sex
Ytest1=test.sex
Xtrain1=train.drop('sex',axis=1)
Xtest1=test.drop('sex',axis=1)


In [ ]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(Xtrain1,Ytrain1)

LogisticRegression(random_state=0)

In [ ]:
y_pred=classifier.predict(Xtest1)

In [ ]:
cm=confusion_matrix(Ytest1,y_pred)
print("Confusion Matrix:\n ",cm)

Confusion Matrix:
  [[23 11]
 [11 20]]


In [ ]:
print("Accuracy: ",accuracy_score(Ytest1,y_pred))

Accuracy:  0.6615384615384615


In [ ]:
pickle.dump(classifier,open(r"C:\Users\neelu\Documents\VIT stuff\sem4\ML\Project 1\model\Logisticregression.pkl",'wb'))